name: Build & Push Frontend to GHCR

on: [push]

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:frontend-latest .
          docker push ghcr.io/${{ github.repository }}:frontend-latest
