name: Build & Deploy Frontend

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create .env.production
        run: echo "${{ secrets.FRONTEND_ENV }}" > .env.production

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/yusufbahtiarr/tickitz:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to VPS via Docker Compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 146.190.102.54
          username: yusuf
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 9701
          script: |
            docker pull ghcr.io/yusufbahtiarr/tickitz:latest
            docker rm -f tickitz || true
            docker run -d -p 9702:80 --name tickitz ghcr.io/yusufbahtiarr/tickitz:latest
